title: <p align="center"> Jibin Kaitharath Baby </p>
logo:  <p align="center">/assets/img/jibin_resized.jpg</p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jibinkaitharath/">LinkedIn</a> |
  <a href="https://github.com/jibinkaitharath">GitHub</a>
  
  <br>   
  I am working as a Software Engineer at Oracle in ERP Systems.
  Previously worked at IBS Software in Cargo management using microservices 
  Having nearly 4 years of experience in the industry, have a passion to learn new things and aspire to transition to a Machine Learning Role.
  <br>
  </p>
theme: jekyll-theme-minimal
