title: <p align="center"> Jibin Kaitharath Baby </p>
logo: /assets/img/jibin_resized_more.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jibinkaitharath/">LinkedIn</a> |
  <a href="https://github.com/jibinkaitharath">GitHub</a>
  
  <br>   
  I am working as a Software Engineer at Oracle in ERP Systems.changed again
  Previously worked at IBS Software in Cargo management using microservices 
  Having nearly 4 years of experience in the industry, have a passion to learn new things and aspire to be a Machine Learning Engineer.
  <br>
  </p>
theme: jekyll-theme-minimal
